package com.iv1201.recruitment.model;

import jakarta.persistence.*;
import java.time.LocalDate;

/**
 * Entity representing an availability period for a person.
 * 
 * Maps directly to the existing "availability" table and specifies
 * periods when a person is available.
 */

@Entity
@Table(name = "availability")
public class Availability {

    /** Primary key, generated by the database */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "availability_id")
    private Long id;

    /** The person this availability belongs to */
    @ManyToOne
    @JoinColumn(name = "person_id")
    private Person person;

    /** Start date of the availability period */
    @Column(name = "from_date")
    private LocalDate fromDate;

    /** End date of the availability period */
    @Column(name = "to_date")
    private LocalDate toDate;

    // ----- Getters and Setters -----
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public LocalDate getFromDate() {
        return fromDate;
    }

    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public LocalDate getToDate() {
        return toDate;
    }

    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }
    
}
