package com.iv1201.recruitment.model;

import jakarta.persistence.*;

/**
 * Entity representing a competence in the system.
 * 
 * Maps directly to the existing "competence" table and represents¨
 * a skill or area of expertise that an applicant can have.
 */
@Entity
@Table(name = "competence")
public class Competence {

    /** Primary key, generated by the database */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "competence_id")
    private Long id;

    /** Name of the competence */
    @Column(name = "name")
    private String name;

    // ----- Getters and Setters -----

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
}
