package com.iv1201.recruitment.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
/**
 * Entity representing a competence profile for an applicant.
 * 
 * Maps directly to the existing "competence_profile" table and
 * links applicants to their competences along with years of experience.
 */
@Entity
@Table(name = "competence_profile")
public class CompetenceProfile {

    /** Primary key, generated by the database */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "competence_profile_id")
    private Long id;

    /** The person this competence profile belongs to */
    @ManyToOne
    @JoinColumn(name = "person_id")
    private Person person;

    /** The competence associated with this profile */
    @ManyToOne
    @JoinColumn(name = "competence_id")
    private Competence competence;

    /** Number of years of experience for the person in this competence */
    @Column(name = "years_of_experience")
    private BigDecimal yearsOfExperience;

    // ----- Getters and Setters -----

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Competence getCompetence() {
        return competence;
    }

    public void setCompetence(Competence competence) {
        this.competence = competence;
    }

    public BigDecimal getYearsOfExperience() {
        return yearsOfExperience;
    }

    public void setYearsOfExperience(BigDecimal yearsOfExperience) {
        this.yearsOfExperience = yearsOfExperience;
    }
    
}
