package com.iv1201.recruitment.model;

import jakarta.persistence.*;

/**
 * Entity representing a person in the recruitment system.
 *
 * Maps directly to the existing "person" table in the database.
 */
@Entity
@Table(name = "person")
public class Person {

    /** Primary key, generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "person_id")
    private Long id;

    /** First name of the person */
    @Column(name = "name")
    private String name;

    /** Surname of the person */
    @Column(name = "surname")
    private String surname;

    /** Personal identification number */
    @Column(name = "pnr")
    private String pnr;

    /** Email address of the person */
    @Column(name = "email")
    private String email;

    /** Username (used for login via auth-service) */
    @Column(name = "username")
    private String username;

    /** Password hash (handled by auth-service in practice) */
    @Column(name = "password")
    private String password;

    /** Role of the person (e.g., applicant, recruiter) */
    @ManyToOne
    @JoinColumn(name = "role_id")
    private Role role;

    // ----- Getters and Setters -----

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getPnr() {
        return pnr;
    }

    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    // Password will eventually be managed by auth-service
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}

