package com.iv1201.recruitment.model;

import jakarta.persistence.*;

/** 
 * Entity representing a role in the system.
 * 
 * Maps directly to the existing "role" table in the database and
 * Typical roles are e.g., APPLICANT, RECRUITER.
 */

@Entity
@Table(name = "role")
public class Role {

    /** Primary key, generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "role_id")
    private Long id;

    /** Name of the role */
    @Column(name = "name")
    private String name;

    // ----- Getters and Setters -----
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
}
